"""empty message

Revision ID: 65082785393c
Revises: 76ea33ae87a5
Create Date: 2023-03-31 21:58:39.424377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65082785393c'
down_revision = '76ea33ae87a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_at_time', sa.Float(), nullable=False))
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.FLOAT(), nullable=False))
        batch_op.drop_column('value_at_time')

    # ### end Alembic commands ###